---
# tasks file for python-services
- name: Set facts.
  ansible.builtin.set_fact:
    python_project_wd: "{{ python_project_repository_path }}/virtual-assistant-listener-py"

- name: Ensure Python, virtualenv and Pip are installed
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
    state: present
    update_cache: true

- name: Install Poetry using Pip
  ansible.builtin.pip:
    name: poetry
    state: present
    virtualenv: "{{ python_project_repository_path }}/.install_venv"

- name: Ensure Python project deps are installed
  become: true
  ansible.builtin.apt:
    name:
      - libportaudio2
      - libatomic1
      - espeak
      - alsa-utils
    state: present
    update_cache: true

- name: Clone private repository using HTTPS and PAT # noqa: latest
  ansible.builtin.git:
    repo: 'https://x-access-token:{{ python_project_github_token }}@github.com/stkr22/virtual-assistant-listener-py.git'
    dest: "{{ python_project_wd }}"
    update: true
    force: true

- name: Install project dependencies using Poetry
  ansible.builtin.shell:
    cmd: "{{ python_project_repository_path }}/.install_venv/bin/poetry install"
    chdir: "{{ python_project_wd }}"
  environment:
    POETRY_VIRTUALENVS_IN_PROJECT: 'true'

- name: Generate .env file from template
  ansible.builtin.template:
    src: env_template.j2
    dest: "{{ python_project_wd }}/.env"
    mode: "0644"

- name: Create asoundrc file.
  ansible.builtin.template:
    src: asoundrc.j2
    dest: "{{ python_asoundrc_target_folder }}/.asoundrc"
    mode: "0644"

- name: Create virtual listener service.
  become: true
  ansible.builtin.template:
    src: virtual_assistant_listener_py.service.j2
    dest: /etc/systemd/system/virtual_assistant_listener_py.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart virtual assistant listener


- name: Flush handlers for immediate systemd restart.
  ansible.builtin.meta: flush_handlers
